import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({}); // uses GEMINI_API_KEY automatically

export async function GET() {
  return NextResponse.json({
    status: "AI API is working",
    model: "gemini-3-flash-preview",
    success: true,
  });
}

export async function POST(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const mode = searchParams.get("mode"); // detect | humanize

    const { text } = await req.json();

    if (!text) {
      return NextResponse.json(
        { error: "Text is required" },
        { status: 400 }
      );
    }

    // ===============================
    // 🧠 1. AI DETECTION MODE
    // ===============================
    if (mode !== "humanize") {
      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: `
        You are an AI detection system.
        Analyze the following text and estimate the probability (0–100%) that it was generated by AI.
        Respond ONLY in pure JSON format:
        {
          "ai_probability": number,
          "human_probability": number,
          "reason": "short explanation"
        }
        Text: """${text}"""
        `,
      });

      let output = response.text;

      if (!output) {
        throw new Error("No output generated from AI model");
      }

      output = output.replace(/```json/g, "").replace(/```/g, "").trim();

      const parsed = JSON.parse(output);

      return NextResponse.json(parsed);
    }

    // ===============================
    // ✍️ 2. HUMANIZE MODE
    // ===============================
    if (mode === "humanize") {
      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: `
        Rewrite the following text to sound natural, human-written, and authentic.
        - Make it less robotic.
        - Improve flow.
        - Add natural phrasing.
        - Avoid AI-like patterns.
        - Keep original meaning.

        Return ONLY the rewritten text.

        Text: """${text}"""
        `,
      });

      const rewrittenText = response.text?.trim();

      if (!rewrittenText) {
        throw new Error("No humanized text generated");
      }

      return NextResponse.json({
        success: true,
        humanized_text: rewrittenText,
      });
    }

  } catch (error) {
    console.error("API ERROR:", error);

    return NextResponse.json(
      {
        error: "Request failed",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
